### ISSUE TITLE
New in the Commons: Provincial Archives of Alberta

### ISSUE THREAD

**Issue by hugovk** [straup/flickr-commons-metadata#11]
New to the Commons:
- Provincial Archives of Alberta  - 95711690@N03

http://blog.flickr.net/en/2014/03/11/welcome-the-provincial-archives-of-alberta-to-the-commons/
https://secure.flickr.com/photos/alberta_archives/

**Comment by hugovk** [comment]
In progress by me.

**Comment by hugovk** [comment]
Added in https://github.com/hugovk/flickr-commons-metadata/commit/20faf8e6b4c94a5433f7c9cfae25256a162a5355

**Comment by straup** [comment]
Awesome. I have the rest of the BL import running in a screen, so I will add this shortly.

**Comment by hugovk** [comment]
Miami added in https://github.com/hugovk/flickr-commons-metadata/commit/65a2ebcc47d94aad0009f5cb4611be720dd505c9 and also in the same PR https://github.com/straup/flickr-commons-metadata/pull/12

**Comment by hugovk** [comment]
Merged in https://github.com/straup/flickr-commons-metadata/pull/12.
