### ISSUE TITLE
Welcome the Tasmanian Archive and Heritage Office to The Commons!

### ISSUE THREAD

**Issue by hugovk** [straup/flickr-commons-metadata#14]
http://blog.flickr.net/en/2014/03/18/welcome-the-tasmanian-archive-and-heritage-office-to-the-commons/
https://www.flickr.com/photos/tasmanianarchiveandheritageoffice
79256815@N03

**Comment by straup** [comment]
In process.

**Comment by straup** [comment]
Done.
