### ISSUE TITLE
Doing pairs of Norways and Swedens

### ISSUE THREAD

**Issue by hugovk** [straup/flickr-commons-metadata#3]
National Library of Norway (48220291@N04)
Riksarkivet (National Archives of Norway) (59811348@N05)
National Library of Sweden (95520404@N07)
Swedish National Heritage Board (34419668@N08)

**Comment by straup** [comment]
https://github.com/straup/flickr-commons-metadata/commit/694780eff9b0c05d3fa798541e17edbdea8cf20c
